---
# tasks file for lighthouse-role
- block:
  - name: Install Lighthouse
    hosts: lighthouse
    become: true
    gather_facts: true

    handlers:
      - name: restart nginx
        ansible.builtin.service:
          name: nginx
          state: restarted

    tasks:
      - name: Install nginx
        ansible.builtin.apt:
          name: nginx
          state: present
          update_cache: true
        tags: nginx

      - name: Download package
        ansible.builtin.git:
          repo: "{{ lighthouse_repo }}"
          dest: "{{ lighthouse_dir }}"
          version: master
        tags: lighthouse

      - name: Deploy nginx template
        ansible.builtin.template:
          src: templates/nginx.conf.j2
          dest: /etc/nginx/nginx.conf
          mode: '0644'
        notify: restart nginx
        tags: config

      - name: Ensure nginx service is enabled and started
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: true
        tags: service
